version: '3.1'

services:

  app:
    image: study_managment
    restart: "no"
    depends_on:
      - db

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: study_managment

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
